const { SlashCommandBuilder } = require('discord.js');
const chistes = [
 '¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter.',
 '¿Cómo se dice pañuelo en chino? Saka-moko.',
 '¿Qué hace una abeja en el gimnasio? Zum-ba.',
 'Mamá, en el colegio me llaman Facebook. ¿Y tú qué les dices? Me gusta.',
 '¿Qué le dice un gusano a otro gusano? Voy a dar una vuelta a la manzana.',
 '¿Cómo se dice pelo sucio en chino? Chin cham pu.',
 '¿Cuál es el animal más antiguo? La cebra, porque está en blanco y negro.',
 '¿Qué le dice una impresora a otra? ¿Esa hoja es tuya o es una impresión mía?',
 '¿Por qué el libro de matemáticas estaba triste? Porque tenía demasiados problemas.',
 '¿Qué hace una abeja en el gimnasio? Zum-ba.',
 '¿Cómo se llama el campeón de buceo japonés? Tokofondo.',
 '¿Cómo se dice barrendero en chino? Kitamoko.',
 '¿Qué hace un pez mago? Nada por aquí, nada por allá.',
 '¿Cómo se llama el campeón de camuflaje? Nadie lo sabe.',
 '¿Qué pasa si pones tu radio en la nevera? Tendrás música fresca.',
 '¿Qué le dice un jardinero a otro? Disfrutemos mientras podamos.',
 '¿Cómo se llama el primo vegano de Bruce Lee? Broco Lee.',
 '¿Qué hace una vaca en el espacio? La Vía Láctea.',
 '¿Cómo se despiden los químicos? Ácido un placer.',
 '¿Qué le dice una pared a otra pared? Nos vemos en la esquina.',
 '¿Cuál es el café más peligroso del mundo? El ex-preso.',
 '¿Cómo se dice explosión en japonés? Saka-Taka.',
 '¿Qué hace una persona con un sobre de ketchup en la oreja? Escuchando salsa.',
 '¿Qué hace un pez en el mar? Nada.',
 '¿Cómo se llama un boomerang que no vuelve? Palo.',
 '¿Qué hace un mudo bailando? Una mudanza.',
 '¿Qué le dice un tomate a otro en una carrera? ¡Ketchup!',
 '¿Cómo se llama un perro mago? Labracadabrador.',
 '¿Por qué los pájaros no usan WhatsApp? Porque ya tienen Twitter.',
 '¿Cuál es el colmo de un electricista? No encontrar su corriente de vida.',
 '¿Cómo se despiden los cables? ¡Nos vemos en un rato!',
 '¿Qué le dice un ganso a otro? ¡Vámonos volando!',
 '¿Qué pasa si mezclas un chicle con una oveja? ¡Te sale un borregomasticable!',
 '¿Qué hace una vaca estudiando? Aprendiendo vaquería.',
 '¿Por qué los pájaros no usan reloj? Porque siempre están en el aire.',
 '¿Cuál es el colmo de un astronauta? Estar en la luna.',
 '¿Qué le dice un celular a otro? No me toques, que tengo saldo.',
 '¿Qué hace un pájaro en un colegio? Aprendiendo a volar.',
 '¿Por qué el océano es tan amigable? Porque siempre te saluda con una ola.',
 '¿Qué hace un huevo en una discoteca? Poner el ritmo.',
 '¿Qué le dice un árbol a otro? Nos vemos en el bosque.',
 '¿Cómo se dice ascensor en japonés? Subeteybajaté.',
 '¿Qué pasa si metes un lápiz en un enchufe? ¡Un cortocircuito artístico!',
 '¿Cómo se llama un delfín que canta? Delfoncio.',
 '¿Qué le dice un pato a otro? ¡Nada!',
 '¿Cómo se dice maquillaje en chino? Te-pinto.',  
 '¿Sabías que el café puede ser peligroso? Si te cae encima, te-mata.',  
 '¿Qué hace una abeja en el gimnasio? Zum-ba.',  
 '¿Cómo se llama el campeón de buceo japonés? Tokofondo.',  
 '¿Cómo se llama el mejor electricista de China? Lu Zen.',  
 '¿Qué le dijo una impresora a otra? Esa hoja es tuya o es impresión mía.',  
 '¿Cómo se despiden los químicos? Ácido un placer.',  
 '¿Qué hace una piedra en el río? Nada.',  
 '¿Cómo se dice pan en japonés? Saka-moto.',  
 '¿Por qué el libro de matemáticas estaba triste? Porque tenía demasiados problemas.',  
 '¿Cómo se dice pelo largo en japonés? Te-kae-ta-ka-beza.',  
 '¿Qué hace un pez mago? Nada por aquí, nada por allá.',  
 '¿Cómo se dice sorpresa en chino? ¡Ala-menkanta!',  
 '¿Qué le dijo el semáforo al coche? No me mires, me estoy cambiando.',  
 '¿Cómo se dice dedo roto en japonés? Chin-garu.',  
 '¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter.',  
 '¿Cómo se dice dos autos chocando en chino? Chinpun-chan.',  
 '¿Cuál es el animal más antiguo? La cebra, porque está en blanco y negro.',  
 '¿Cómo se llama el líder de los electricistas chinos? Enchúfate Ling.',  
 '¿Por qué el tomate no dio más? Porque ya estaba ketchup.',  
 '¿Cómo se dice puerta rota en japonés? No sir-be.',  
 '¿Qué hace un perro con un taladro? Taladrando.',  
 '¿Cómo se dice flor en chino? Flon.',  
 '¿Por qué el agua no tiene forma? Porque siempre se adapta.',  
 '¿Cómo se llama el mejor basquetbolista de China? Chin basket.',  
 '¿Cómo se llama el campeón de karate? Toko duro.',
 '¿Qué hace un perro con un taladro? Perforar.',
 '¿Qué hace una abeja en el teléfono? Llamar a su abejamiga.'
];
module.exports = {
 data: new SlashCommandBuilder()
  .setName('chiste')
  .setDescription('Cuenta un chiste aleatorio.'),
 async execute(interaction) {
  const chisteAleatorio = chistes[Math.floor(Math.random() * chistes.length)];
  await interaction.reply(chisteAleatorio);
 }
};